### ISSUE TITLE
Target a port other than 3306

### ISSUE THREAD

**Issue by jasonamyers** [joereynolds/gauxilium#104]
It would be great if we could pass in a port in the configuration or from the command line.

**Comment by joereynolds** [comment]
Sorry for the late reply. Very good point, It's on the list

- [ ] - It looks like `any-db` can take an object instead of URL for creating connections. We should make the configuration a direct mapping to this. This gives us more flexibility (since we can use anything and everything that any-db gives us) and we can remove any logic around creating a connection since we're literally passing the user's configuration straight through.

**Comment by joereynolds** [comment]
References on how to create a connection using an object (Doesn't seem to work in typescript?)

https://github.com/drivefast/node-cipherwallet/blob/976c12b9d1973605db388f219693c70b7c90f0be/cipherwallet/db_interface.js

https://github.com/cuauhtlahuac/MySql_Test/blob/cde8198038be1fa4a216f166b262798f0d4b15cb/MySql_test/app.js

https://github.com/ltjwin/cs132-final-project/blob/379bcf9658a12cb33bee13606b2b2681cb41526e/weatherwarnings0507/server.js

https://github.com/jnterry/db-connection-promise/blob/13cf10ad8527124767490d77252e9025143144eb/examples/01-connect-and-query/mysql-standalone.js

**Comment by joereynolds** [comment]
Hey Jason, this is done, thanks for the suggestion!

**Comment by jasonamyers** [comment]
Awesome thank you so much for this and a great tool
